FROM alpine:3.5
MAINTAINER "Joan Ardiaca Jové"

# Base packages
RUN apk add --no-cache python3 python3-dev alpine-sdk apache2-dev
RUN pip3 install mod_wsgi

CMD cat /usr/lib/python3.5/site-packages/mod_wsgi/server/mod_wsgi-py35.cpython-35m-x86_64-linux-gnu.so

