# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('arrest_order', 'arrest_order'), ('ban', 'ban'), ('policy', 'policy')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_position', models.BooleanField()),
                ('inherit_capabilities', models.BooleanField(help_text='If true, capabilities of parents and leader apply to this organization too')),
                ('violence_monopoly', models.BooleanField(default=False)),
                ('decision_taking', models.CharField(choices=[('democratic', 'democratic'), ('autocratic', 'autocratic'), ('distributed', 'distributed')], max_length=15)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaded_organizations', to='organization.Organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PolicyDocument')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('draft', models.BooleanField()),
                ('proposal', models.BooleanField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PolicyDocument')),
            ],
        ),
        migrations.AddField(
            model_name='capability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
