# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_world_description'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='world',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.World'),
            preserve_default=False,
        ),
    ]
