# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionelectionvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='positionelection',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='positionelection',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.PositionCandidacy'),
        ),
        migrations.AddField(
            model_name='positioncandidacy',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='positioncandidacy',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PositionElection'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.PolicyDocument'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='from_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_stemming', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationrelationship',
            name='to_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_receiving', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='character_members',
            field=models.ManyToManyField(blank=True, to='world.Character'),
        ),
        migrations.AddField(
            model_name='organization',
            name='current_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.PositionElection'),
        ),
        migrations.AddField(
            model_name='organization',
            name='heir_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_heir_to', to='world.Character'),
        ),
        migrations.AddField(
            model_name='organization',
            name='heir_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_heir_to', to='world.Character'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.PositionElection'),
        ),
        migrations.AddField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaded_organizations', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_members',
            field=models.ManyToManyField(blank=True, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
        migrations.AddField(
            model_name='militarystance',
            name='from_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mil_stances_stemming', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='militarystance',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.Tile'),
        ),
        migrations.AddField(
            model_name='militarystance',
            name='to_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mil_stances_receiving', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='capabilityvote',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CapabilityProposal'),
        ),
        migrations.AddField(
            model_name='capabilityvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='capabilityproposal',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Capability'),
        ),
        migrations.AddField(
            model_name='capabilityproposal',
            name='proposing_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='capability',
            name='applying_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities_to_this', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='capability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='capability',
            name='stemming_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='organization.Capability'),
        ),
        migrations.AlterUniqueTogether(
            name='positionelectionvote',
            unique_together=set([('election', 'voter')]),
        ),
        migrations.AlterUniqueTogether(
            name='positioncandidacy',
            unique_together=set([('election', 'candidate')]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrelationship',
            unique_together=set([('from_organization', 'to_organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='militarystance',
            unique_together=set([('from_organization', 'to_organization', 'region')]),
        ),
    ]
