# Generated by Django 2.1 on 2018-08-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171119_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilityproposal',
            name='proposing_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character'),
        ),
        migrations.AlterField(
            model_name='capabilityvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='current_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.PositionElection'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='heir_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_heir_to', to='character.Character'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='heir_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_heir_to', to='character.Character'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.PositionElection'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaded_organizations', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.PolicyDocument'),
        ),
        migrations.AlterField(
            model_name='positioncandidacy',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character'),
        ),
        migrations.AlterField(
            model_name='positionelection',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.PositionCandidacy'),
        ),
        migrations.AlterField(
            model_name='positionelectionvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character'),
        ),
    ]
