# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_tile_controlled_by'),
        ('organization', '0002_organization_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(to='world.Character'),
        ),
    ]
