# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='type',
            field=models.CharField(choices=[('arrest_order', 'ordering arrests'), ('ban', 'banning'), ('policy', 'writing policy and law')], max_length=15),
        ),
    ]
