# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organization_barbaric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='type',
            field=models.CharField(choices=[('ban', 'ban'), ('policy', 'write policy and law'), ('diplomacy', 'conduct diplomacy'), ('conscript', 'conscript troops'), ('suborganizations', 'manage subordinate organizations'), ('memberships', 'manage memberships'), ('heir', 'set heir'), ('elect', 'elect'), ('candidacy', 'present candidacy'), ('convoke elections', 'convoke elections'), ('military stance', 'military orders'), ('battle formation', 'battle formation'), ('occupy region', 'occupy region'), ('take grain', 'take grain'), ('manage guilds', 'manage guilds'), ('manage taxation', 'manage taxation')], max_length=20),
        ),
    ]
