# Generated by Django 2.1 on 2018-09-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180819_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capability',
            name='type',
            field=models.CharField(choices=[('ban', 'ban'), ('policy', 'write policy and law'), ('diplomacy', 'conduct diplomacy'), ('conscript', 'conscript troops'), ('heir', 'set heir'), ('elect', 'elect'), ('candidacy', 'present candidacy'), ('convoke elections', 'convoke elections'), ('military stance', 'military orders'), ('battle formation', 'battle formation'), ('occupy region', 'occupy region'), ('take grain', 'take grain'), ('manage guilds', 'manage guilds'), ('manage taxation', 'manage taxation'), ('arrest warrant', 'arrest warrant')], max_length=20),
        ),
    ]
