# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170511_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_countdown',
            field=models.SmallIntegerField(default=0),
        ),
    ]
