# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organization_tax_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityproposal',
            name='democratic',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
