# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20170314_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policydocument',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
