# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20170317_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityproposal',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capabilityproposal',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
