# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20170321_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='color',
            field=models.CharField(default='FFFFFF', help_text='Format: RRGGBB (hex)', max_length=6),
        ),
    ]
