# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_auto_20170322_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PositionElection'),
        ),
    ]
