# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_auto_20170323_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioncandidacy',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
