# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('organization', '0032_auto_20170326_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryStance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_type', models.CharField(choices=[('avoid battle', 'avoid battle'), ('defensive', 'defensive'), ('aggressive', 'aggressive')], max_length=20)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mil_stances_stemming', to='organization.Organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.Tile')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mil_stances_receiving', to='organization.Organization')),
            ],
        ),
        migrations.AlterField(
            model_name='capability',
            name='type',
            field=models.CharField(choices=[('ban', 'ban'), ('policy', 'write policy and law'), ('diplomacy', 'conduct diplomacy'), ('conscript', 'conscript troops'), ('dissolve', 'dissolve'), ('suborganizations', 'manage subordinate organizations'), ('secede', 'secede'), ('memberships', 'manage memberships'), ('heir', 'set heir'), ('elect', 'elect'), ('candidacy', 'present candidacy'), ('convoke elections', 'convoke elections'), ('military stance', 'military orders')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='militarystance',
            unique_together=set([('from_organization', 'to_organization', 'region')]),
        ),
    ]
