# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20170331_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarystance',
            name='stance_type',
            field=models.CharField(blank=True, choices=[('avoid battle', 'avoid battle'), ('defensive', 'defensive'), ('aggressive', 'aggressive')], max_length=20, null=True),
        ),
    ]
