# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_auto_20170331_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarystance',
            name='stance_type',
            field=models.CharField(choices=[('avoid battle', 'avoid battle'), ('defensive', 'defensive'), ('aggressive', 'aggressive')], default='default', max_length=20),
        ),
    ]
