# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170303_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='members',
            new_name='character_members',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='parent',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='election_period_months',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='last_election',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_type',
            field=models.CharField(choices=[('character', 'character'), ('organization', 'organization')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_members',
            field=models.ManyToManyField(to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner_and_leader_locked',
            field=models.BooleanField(default=False, help_text="If set, this organization will have always the same leader as it's owner."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='inherit_capabilities',
            field=models.BooleanField(help_text='If true, capabilities of parents and leader apply to this organization toto'),
        ),
    ]
