# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170311_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.AlterField(
            model_name='organization',
            name='inherit_capabilities',
            field=models.BooleanField(help_text='If true, capabilities of parents and leader apply to this organization too'),
        ),
    ]
