# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170311_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='election_period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_election',
            field=models.IntegerField(default=0),
        ),
    ]
