# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20170314_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydocumentversion',
            name='draft',
        ),
        migrations.AddField(
            model_name='policydocument',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.PolicyDocumentVersion'),
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.PolicyDocument'),
        ),
    ]
