# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20170314_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='last_modified_turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
