# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('organization', '0015_auto_20170316_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_json', models.TextField()),
                ('vote_end_turn', models.IntegerField()),
                ('executed', models.BooleanField()),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Capability')),
                ('proposing_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yea', 'yea'), ('nay', 'nay'), ('invalid', 'invalid')], max_length=10)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CapabilityProposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationDecision',
        ),
        migrations.AlterField(
            model_name='organization',
            name='decision_taking',
            field=models.CharField(choices=[('democratic', 'democratic'), ('distributed', 'distributed')], max_length=15),
        ),
    ]
