# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_organization_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='inherit_capabilities',
        ),
        migrations.AddField(
            model_name='organization',
            name='position_type',
            field=models.CharField(blank=True, choices=[('inherited', 'inherited'), ('elected', 'elected')], default='', max_length=15),
        ),
    ]
