# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('organization', '0021_auto_20170322_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='heir_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_heir_to', to='world.Character'),
        ),
        migrations.AddField(
            model_name='organization',
            name='heir_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_heir_to', to='world.Character'),
        ),
    ]
