# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20170322_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='next_election',
            field=models.IntegerField(default=0),
        ),
    ]
