# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20170322_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.PositionElection'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.PositionElection'),
        ),
    ]
