# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('organization', '0027_auto_20170322_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positioncandidate',
            unique_together=set([('election', 'candidate')]),
        ),
        migrations.AlterUniqueTogether(
            name='positionelectionvote',
            unique_together=set([('election', 'voter')]),
        ),
    ]
