# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_positioncandidacy_retired'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('war', 'war'), ('banned', 'banned'), ('friendship', 'friendship'), ('defensive alliance', 'defensive alliance'), ('alliance', 'alliance')], max_length=20, null=True)),
                ('desired_relationship', models.CharField(blank=True, choices=[('war', 'war'), ('banned', 'banned'), ('friendship', 'friendship'), ('defensive alliance', 'defensive alliance'), ('alliance', 'alliance')], max_length=20, null=True)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_stemming', to='organization.Organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_receiving', to='organization.Organization')),
            ],
        ),
        migrations.AlterField(
            model_name='capability',
            name='type',
            field=models.CharField(choices=[('ban', 'ban'), ('policy', 'write policy and law'), ('diplomacy', 'conduct diplomacy'), ('conscript', 'conscript troops'), ('dissolve', 'dissolve'), ('suborganizations', 'manage subordinate organizations'), ('secede', 'secede'), ('memberships', 'manage memberships'), ('heir', 'set heir'), ('elect', 'elect'), ('candidacy', 'present candidacy'), ('convoke elections', 'convoke elections')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='organizationrelationship',
            unique_together=set([('from_organization', 'to_organization')]),
        ),
    ]
