# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20170326_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrelationship',
            name='desired_relationship',
            field=models.CharField(blank=True, choices=[('peace', 'peace'), ('war', 'war'), ('banned', 'banned'), ('friendship', 'friendship'), ('defensive alliance', 'defensive alliance'), ('alliance', 'alliance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrelationship',
            name='relationship',
            field=models.CharField(choices=[('peace', 'peace'), ('war', 'war'), ('banned', 'banned'), ('friendship', 'friendship'), ('defensive alliance', 'defensive alliance'), ('alliance', 'alliance')], default='peace', max_length=20),
        ),
    ]
