# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_auto_20170331_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarystance',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.Tile'),
        ),
        migrations.AlterField(
            model_name='militarystance',
            name='stance_type',
            field=models.CharField(choices=[('avoid battle', 'avoid battle'), ('defensive', 'defensive'), ('aggressive', 'aggressive')], default='defensive', max_length=20),
        ),
    ]
