# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_auto_20170331_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarystance',
            name='stance_type',
            field=models.CharField(choices=[('default', 'automatic by diplomatic relationship'), ('avoid battle', 'avoid battle'), ('defensive', 'defensive'), ('aggressive', 'aggressive')], default='default', max_length=20),
        ),
    ]
