# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recruitment_type', models.CharField(choices=[('conscription', 'conscription'), ('professional', 'professional'), ('mercenary', 'mercenary')], max_length=30)),
                ('type', models.CharField(choices=[('infantry', 'infantry'), ('pikemen', 'pikemen'), ('archers', 'archers'), ('cavalry', 'cavalry'), ('catapult', 'catapult'), ('siege tower', 'siege tower'), ('ram', 'ram')], max_length=30)),
                ('status', models.CharField(choices=[('not mobilized', 'not mobilized'), ('training', 'training'), ('standing', 'standing'), ('following', 'following'), ('customer search', 'customer search')], max_length=30)),
                ('mobilization_status_since', models.IntegerField()),
                ('current_status_since', models.IntegerField()),
                ('battle_line', models.IntegerField(choices=[(0, 'advanced line'), (1, 'front line'), (2, 'middle line'), (3, 'rear line'), (4, 'rearguard')], default=3)),
                ('battle_side_pos', models.IntegerField(choices=[(-5, 'flanking far left'), (-4, 'flanking left'), (-3, 'cover left flank'), (-2, 'left side'), (-1, 'left-center'), (0, 'center'), (1, 'right-center'), (2, 'right side'), (3, 'cover right flank'), (4, 'flanking right'), (5, 'flanking far right')], default=0)),
                ('generation_size', models.IntegerField(default=0, help_text='Only used in tests that need generated units')),
                ('default_battle_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Order')),
            ],
        ),
    ]
