# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='worldunit',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_originating', to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='worldunit',
            name='owner_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='worldunit',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
    ]
