# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_auto_20171119_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='owners_debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
