# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_worldunit_owners_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='owners_debt',
            field=models.IntegerField(default=0),
        ),
    ]
