# Generated by Django 2.1 on 2018-08-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0006_remove_worldunit_owners_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='auto_pay',
            field=models.BooleanField(default=False, help_text='Unit is paid automatically from character cash each turn.'),
        ),
    ]
