# Generated by Django 2.1 on 2018-08-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0007_worldunit_auto_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='recruitment_type',
            field=models.CharField(choices=[('conscripted', 'conscripted'), ('professional', 'professional'), ('mercenary', 'mercenary'), ('raised', 'raised')], max_length=30),
        ),
    ]
