# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('creation_turn', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('travel', 'travel'), ('conquest', 'conquest'), ('turn', 'new turn'), ('proposal', 'action proposal'), ('battle', 'battle'), ('policy', 'policy and law'), ('ban', 'ban'), ('elections', 'elections'), ('diplomacy', 'diplomacy'), ('military stance', 'military stance'), ('battle formation', 'battle formation'), ('conquest', 'conquest'), ('guilds', 'guilds'), ('unit', 'unit'), ('welcome', 'welcome'), ('heir', 'heir'), ('leaving', 'leaving'), ('taxes', 'taxes'), ('newcomer', 'newcomer'), ('pause', 'pause'), ('cash transfer', 'cash transfer')], max_length=20, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['creation_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('html_content', models.TextField()),
                ('display_order', models.SmallIntegerField()),
                ('draft', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
