# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterNofitication',
            new_name='CharacterNotification',
        ),
    ]
