# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20170430_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermessage',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
