# Generated by Django 2.1 on 2018-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20180819_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermessage',
            name='category',
        ),
        migrations.AddField(
            model_name='charactermessage',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
