# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_charactermessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermessage',
            name='safe',
            field=models.BooleanField(default=False),
        ),
    ]
