# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('organization', '0032_auto_20170326_2302'),
        ('messaging', '0009_messagerelationship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereceiver',
            unique_together=set([('message', 'character')]),
        ),
        migrations.AlterUniqueTogether(
            name='messagereceivergroup',
            unique_together=set([('message', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='messagerelationship',
            unique_together=set([('from_character', 'to_character')]),
        ),
    ]
