# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20170328_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageReceiver',
            new_name='MessageRecipient',
        ),
        migrations.RenameModel(
            old_name='MessageReceiverGroup',
            new_name='MessageRecipientGroup',
        ),
    ]
