# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_auto_20170328_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermessage',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'travel'), ('conquest', 'conquest')], max_length=20, null=True),
        ),
    ]
