# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=1, help_text='Go from 1 to 5')),
                ('type', models.CharField(choices=[('grain field', 'grain field'), ('residence', 'residence'), ('sawmill', 'sawmill'), ('iron mine', 'iron mine'), ('granary', 'granary'), ('prison', 'prison')], max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(blank=True, help_text="NULL means 'owned by local population'", null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cash', models.IntegerField(default=0)),
                ('hours_in_turn_left', models.IntegerField(default=360)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('male', models.BooleanField()),
                ('able', models.BooleanField()),
                ('age_months', models.IntegerField()),
                ('trained_soldier', models.BooleanField(default=None)),
                ('skill_fighting', models.IntegerField()),
            ],
            options={
                'base_manager_name': 'stats_manager',
            },
            managers=[
                ('stats_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.FloatField()),
                ('z_pos', models.IntegerField()),
                ('type', models.CharField(choices=[('plains', 'plains'), ('forest', 'forest'), ('shore', 'shore'), ('deepsea', 'deep sea'), ('mountain', 'mountain')], max_length=15)),
                ('controlled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conquest', 'conquest')], db_index=True, max_length=20)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('start_turn', models.IntegerField()),
                ('end_turn', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tile')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('initialized', models.BooleanField(default=False)),
                ('current_turn', models.IntegerField(default=0)),
                ('blocked_for_turn', models.BooleanField(default=False, help_text='True during turn processing')),
            ],
        ),
        migrations.CreateModel(
            name='WorldUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recruitment_type', models.CharField(choices=[('conscription', 'conscription'), ('professional', 'professional'), ('mercenary', 'mercenary')], max_length=30)),
                ('type', models.CharField(choices=[('infantry', 'infantry'), ('pikemen', 'pikemen'), ('archers', 'archers'), ('cavalry', 'cavalry'), ('catapult', 'catapult'), ('siege tower', 'siege tower'), ('ram', 'ram')], max_length=30)),
                ('status', models.CharField(choices=[('not mobilized', 'not mobilized'), ('training', 'training'), ('standing', 'standing'), ('following', 'following'), ('customer search', 'customer search')], max_length=30)),
                ('mobilization_status_since', models.IntegerField()),
                ('current_status_since', models.IntegerField()),
                ('battle_line', models.IntegerField(choices=[(0, 'Advanced line'), (1, 'Front line'), (2, 'Middle line'), (3, 'Rear line'), (4, 'Rearguard')], default=3)),
                ('battle_side_pos', models.IntegerField(choices=[(-5, 'Flanking far left'), (-4, 'Flanking left'), (-3, 'Cover left flank'), (-2, 'Left side'), (-1, 'Left-center'), (0, 'Center'), (1, 'Right-center'), (2, 'Right side'), (3, 'Cover right flank'), (4, 'Flanking right'), (5, 'Flanking far right')], default=0)),
                ('generation_size', models.IntegerField(default=0, help_text='Only used in tests that need generated units')),
                ('default_battle_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Order')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Settlement')),
                ('owner_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World')),
            ],
        ),
        migrations.AddField(
            model_name='tile',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tile'),
        ),
        migrations.AddField(
            model_name='region',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
        migrations.AddField(
            model_name='npc',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='npc',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='npc',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='world.Building'),
        ),
        migrations.AddField(
            model_name='npc',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to='world.WorldUnit'),
        ),
        migrations.AddField(
            model_name='npc',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='world.Building'),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='character',
            name='oath_sworn_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='character',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='travel_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travellers_heading', to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
        migrations.AddField(
            model_name='building',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
        ),
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together=set([('world', 'x_pos', 'z_pos')]),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('world', 'name')]),
        ),
    ]
