# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=15)),
                ('macro_x', models.IntegerField()),
                ('macro_z', models.IntegerField()),
                ('micro_x', models.IntegerField()),
                ('micro_z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worldunit',
            name='owner_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
    ]
