# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='wound_status',
            field=models.SmallIntegerField(choices=[(0, 'uninjured'), (1, 'lightly wounds'), (2, 'wounded'), (3, 'heavy wounds'), (4, 'dead')], default=0),
        ),
    ]
