# Generated by Django 2.1 on 2018-08-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20171201_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileevent',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="NULL means 'owned by local population'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='world.Building'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.Character'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='world.Settlement'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offspring', to='world.Settlement'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident', to='world.Building'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldier', to='unit.WorldUnit'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to='world.Building'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='controlled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='tileevent',
            name='counter',
            field=models.IntegerField(blank=True, help_text='Counter for general use', null=True),
        ),
        migrations.AlterField(
            model_name='tileevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
    ]
