# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20170502_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='wound_status',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
    ]
