# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_delete_unitorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorldRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('type', models.CharField(max_length=15)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.WorldRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.World'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldunit',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.WorldRegion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldunit',
            name='world',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.World'),
            preserve_default=False,
        ),
    ]
