# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_npc_wound_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='field_production_counter',
            field=models.IntegerField(default=0),
        ),
    ]
