# Generated by Django 2.1 on 2018-08-19 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20180819_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileevent',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
