# Generated by Django 2.1 on 2018-08-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_tileevent_create_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='bureaucratic_work',
        ),
        migrations.AddField(
            model_name='settlement',
            name='public_order',
            field=models.IntegerField(default=1000, help_text='0-1000, shown as %'),
        ),
    ]
