# Generated by Django 2.1 on 2018-08-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20180819_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='unit_debt',
            field=models.IntegerField(default=0, help_text='Silver coins owed to NPC'),
        ),
        migrations.AddField(
            model_name='npc',
            name='unit_morale',
            field=models.IntegerField(default=0, help_text='Unit morale, 0 to 1000'),
        ),
    ]
