# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='hunger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
