# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_auto_20161123_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World')),
            ],
        ),
        migrations.AddField(
            model_name='tile',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.Region'),
            preserve_default=False,
        ),
    ]
