# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_npc_hunger'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='population_default',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settlement',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
