# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_auto_20161123_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together=set([('world', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together=set([('world', 'x_pos', 'z_pos')]),
        ),
    ]
