# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_auto_20170511_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('grain field', 'grain field'), ('residence', 'residence'), ('granary', 'granary'), ('prison', 'prison'), ('guild', 'guild')], max_length=15),
        ),
    ]
