# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_auto_20170511_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='guilds_setting',
            field=models.CharField(choices=[('prohibit guilds', 'prohibit guilds'), ('restrict guilds', 'restrict guilds'), ('keep guilds', 'keep guilds'), ('promote guilds', 'promote guilds')], default='keep guilds', max_length=20),
        ),
    ]
