# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_world'),
        ('world', '0010_world_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='controlled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
