# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_auto_20170514_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='units_originating', to='world.Settlement'),
            preserve_default=False,
        ),
    ]
