# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_worldunit_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
        ),
        migrations.AlterField(
            model_name='worldunit',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
    ]
