# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_auto_20170516_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.CharField(choices=[('commander', 'commander'), ('trader', 'trader'), ('bureaucrat', 'bureaucrat')], default='commander', max_length=20),
            preserve_default=False,
        ),
    ]
