# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_auto_20170303_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('pos_x', models.SmallIntegerField()),
                ('pos_y', models.SmallIntegerField()),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tile')),
            ],
        ),
        migrations.AddField(
            model_name='world',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
