# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_character_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='battle_line',
            field=models.IntegerField(choices=[(0, 'advanced line'), (1, 'front line'), (2, 'middle line'), (3, 'rear line'), (4, 'rearguard')], default=3),
        ),
        migrations.AlterField(
            model_name='worldunit',
            name='battle_side_pos',
            field=models.IntegerField(choices=[(-5, 'flanking far left'), (-4, 'flanking left'), (-3, 'cover left flank'), (-2, 'left side'), (-1, 'left-center'), (0, 'center'), (1, 'right-center'), (2, 'right side'), (3, 'cover right flank'), (4, 'flanking right'), (5, 'flanking far right')], default=0),
        ),
        migrations.AlterIndexTogether(
            name='npc',
            index_together=set([('residence', 'hunger')]),
        ),
    ]
