# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_auto_20170521_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='public_order',
            field=models.IntegerField(default=1000, help_text='0-1000, shown as %'),
        ),
    ]
