# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_auto_20170625_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_activation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
