# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_auto_20170303_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='able',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npc',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('grain field', 'grain field'), ('residence', 'residence'), ('sawmill', 'sawmill'), ('iron mine', 'iron mine'), ('granary', 'granary'), ('prison', 'prison')], max_length=15),
        ),
    ]
