# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0023_auto_20170309_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldunit',
            name='region',
        ),
        migrations.AddField(
            model_name='worldunit',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldunit',
            name='status',
            field=models.CharField(choices=[('not mobilized', 'not mobilized'), ('training', 'training'), ('standing', 'standing'), ('following', 'following'), ('customer search', 'customer search')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worldunit',
            name='owner_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AlterField(
            model_name='worldunit',
            name='recruitment_type',
            field=models.CharField(choices=[('conscription', 'conscription'), ('professional', 'professional'), ('mercenary', 'mercenary')], max_length=30),
        ),
    ]
