# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0025_worldunit_mobilization_status_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='current_status_since',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
