# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0026_worldunit_current_status_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'base_manager_name': 'stats_manager'},
        ),
        migrations.AlterModelManagers(
            name='npc',
            managers=[
                ('stats_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
