# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='generation_size',
            field=models.IntegerField(default=0, help_text='Only used in tests that need generated units'),
        ),
    ]
