# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_worldunit_generation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='battle_line',
            field=models.IntegerField(choices=[(1, 'Advanced line'), (2, 'Front line'), (3, 'Middle line'), (4, 'Rear line'), (5, 'Rearguard')], default=3),
        ),
        migrations.AddField(
            model_name='worldunit',
            name='battle_side_pos',
            field=models.IntegerField(choices=[(-5, 'Flanking far left'), (-4, 'Flanking left'), (-3, 'Cover left flank'), (-2, 'Left side'), (-1, 'Left-center'), (0, 'Center'), (1, 'Right-center'), (2, 'Right side'), (3, 'Cover right flank'), (4, 'Flanking right'), (5, 'Flanking far right')], default=0),
        ),
    ]
