# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0030_auto_20170405_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='battle_line',
            field=models.IntegerField(choices=[(0, 'Advanced line'), (1, 'Front line'), (2, 'Middle line'), (3, 'Rear line'), (4, 'Rearguard')], default=3),
        ),
    ]
