# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0032_worldunit_default_battle_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldunit',
            name='default_battle_orders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.Order'),
            preserve_default=False,
        ),
    ]
