# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20170404_1704'),
        ('world', '0033_auto_20170413_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conquest', 'conquest')], max_length=20)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tile')),
            ],
        ),
    ]
