# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0034_tileevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileevent',
            name='end_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tileevent',
            name='start_turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tileevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='tileevent',
            name='type',
            field=models.CharField(choices=[('conquest', 'conquest')], db_index=True, max_length=20),
        ),
    ]
