# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20161029_1730'),
        ('battle', '0003_auto_20161026_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
            ],
        ),
    ]
