# Generated by Django 2.1 on 2018-08-19 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20180819_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterevent',
            options={'ordering': ['create_timestamp']},
        ),
    ]
