# Generated by Django 2.1 on 2018-09-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180909_2347'),
        ('character', '0005_auto_20180819_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
    ]
