# Generated by Django 2.1 on 2018-09-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_characterevent_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterevent',
            name='type',
            field=models.CharField(choices=[('recruit_unit', 'recruit_unit'), ('travel', 'travel'), ('pause', 'pause'), ('unpause', 'unpause'), ('raise_unit', 'raise_unit'), ('bureaucratic_work', 'bureaucratic_work'), ('arrest_warrant', 'arrest_warrant')], db_index=True, max_length=20),
        ),
    ]
