# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20161029_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOrder',
        ),
    ]
