# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_worldregion_y_pos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorldRegion',
            new_name='Tile',
        ),
    ]
