# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_auto_20170303_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='pos_y',
        ),
        migrations.AddField(
            model_name='settlement',
            name='x_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='z_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
