# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170303_1436'),
        ('world', '0015_auto_20170303_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=1)),
                ('type', models.CharField(choices=[('residence', 'residence'), ('sawmill', 'sawmill'), ('iron mine', 'iron mine'), ('prison', 'prison')], max_length=15)),
                ('quantity', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Settlement')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField()),
                ('age_months', models.IntegerField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to='world.Building')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='region',
        ),
        migrations.RemoveField(
            model_name='worldunit',
            name='power',
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.Settlement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tile',
            name='type',
            field=models.CharField(choices=[('plains', 'plains'), ('forest', 'forest'), ('shore', 'shore'), ('deepsea', 'deep sea'), ('mountain', 'mountain')], max_length=15),
        ),
        migrations.AddField(
            model_name='npc',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldier', to='world.WorldUnit'),
        ),
        migrations.AddField(
            model_name='npc',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='world.Building'),
        ),
    ]
