# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_auto_20170303_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
