# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0018_auto_20170305_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='recruitment_type',
            field=models.CharField(choices=[('conscripted', 'conscripted'), ('professional', 'professional'), ('mercenary', 'mercenary')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldunit',
            name='type',
            field=models.CharField(choices=[('infantry', 'infantry'), ('pikemen', 'pikemen'), ('archers', 'archers'), ('cavalry', 'cavalry'), ('catapult', 'catapult'), ('siege tower', 'siege tower'), ('ram', 'ram')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
