# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_auto_20170305_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hours_in_turn_left',
            field=models.IntegerField(default=360),
        ),
    ]
