# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0020_character_hours_in_turn_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='travel_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travellers_heading', to='world.Settlement'),
        ),
        migrations.AddField(
            model_name='world',
            name='blocked_for_turn',
            field=models.BooleanField(default=False, help_text='True during turn processing'),
        ),
    ]
