# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_auto_20170307_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offspring', to='world.Settlement'),
            preserve_default=False,
        ),
    ]
