# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0024_auto_20170309_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldunit',
            name='mobilization_status_since',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
