# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0027_auto_20170311_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='level',
            field=models.SmallIntegerField(default=1, help_text='Go from 1 to 5'),
        ),
        migrations.AlterField(
            model_name='building',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="NULL means 'owned by local population'", null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
