# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0021_auto_20170307_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterNofitication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('creation_turn', models.IntegerField()),
                ('read', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
            ],
        ),
    ]
