# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20170308_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('html_content', models.TextField()),
                ('display_order', models.SmallIntegerField()),
                ('draft', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='characternotification',
            options={'ordering': ['creation_time']},
        ),
    ]
