# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('messaging', '0004_auto_20170327_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('creation_turn', models.IntegerField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='world.Character')),
            ],
            options={
                'ordering': ['creation_time'],
            },
        ),
        migrations.RemoveField(
            model_name='characternotification',
            name='character',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterField(
            model_name='messagereceiver',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.CharacterMessage'),
        ),
        migrations.AlterField(
            model_name='messagereceivergroup',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.CharacterMessage'),
        ),
        migrations.DeleteModel(
            name='CharacterNotification',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
