# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20170327_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermessage',
            name='category',
            field=models.CharField(blank=True, choices=[('travel', 'travel')], max_length=20, null=True),
        ),
    ]
