# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('messaging', '0008_messagereceiver_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_relationships_to', to='world.Character')),
            ],
        ),
    ]
