# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0028_auto_20170316_2311'),
        ('messaging', '0011_auto_20170328_2047'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='messagerecipient',
            index_together=set([('character', 'read')]),
        ),
    ]
