# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('started', models.BooleanField(default=False)),
                ('start_turn', models.IntegerField()),
                ('end_turn', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_in_battle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BattleCharacterInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BattleContubernium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_x_pos', models.IntegerField(default=0)),
                ('starting_z_pos', models.IntegerField(default=0)),
                ('x_offset_to_unit', models.IntegerField(default=0, help_text='Offset to BattleUnit starting_pos')),
                ('z_offset_to_unit', models.IntegerField(default=0)),
                ('x_offset_to_formation', models.IntegerField(default=0)),
                ('z_offset_to_formation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BattleContuberniumInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('moved_this_turn', models.BooleanField(default=False)),
                ('desires_pos', models.BooleanField(default=False)),
                ('desired_x_pos', models.IntegerField(blank=True, null=True)),
                ('desired_z_pos', models.IntegerField(blank=True, null=True)),
                ('ammo_remaining', models.PositiveIntegerField()),
                ('attack_type_this_turn', models.CharField(blank=True, choices=[('melee', 'melee attack'), ('ranged', 'ranged attack')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('line', 'line'), ('column', 'column'), ('square', 'square'), ('wedge', 'wedge'), ('iwedge', 'iwedge')], max_length=15)),
                ('element_size', models.IntegerField(blank=True, null=True)),
                ('spacing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattleObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BattleObjectInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BattleOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BattleSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BattleSoldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BattleSoldierInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_status', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BattleTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BattleUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_x_pos', models.IntegerField(default=0)),
                ('starting_z_pos', models.IntegerField(default=0)),
                ('starting_manpower', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('in_battle', models.BooleanField(default=True)),
                ('battle_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleOrganization')),
                ('battle_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleSide')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='BattleUnitInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('battle_character_in_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacterInTurn')),
                ('battle_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn')),
                ('battle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(choices=[('stand', 'stand'), ('move', 'move'), ('flee', 'flee'), ('charge', 'charge'), ('formation', 'formation'), ('ranged and charge', 'ranged attack, then charge'), ('ranged and flee', 'ranged attack, then flee'), ('ranged and stand', 'ranged attack, then stand'), ('stand and keep distance', 'stand and keep distance')], max_length=15)),
                ('target_location_x', models.IntegerField(null=True)),
                ('target_location_z', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='battleunitinturn',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.Order'),
        ),
    ]
