# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle', '0001_initial'),
        ('organization', '0001_initial'),
        ('world', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='world_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.WorldUnit'),
        ),
        migrations.AddField(
            model_name='battleturn',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle'),
        ),
        migrations.AddField(
            model_name='battlesoldierinturn',
            name='battle_contubernium_in_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContuberniumInTurn'),
        ),
        migrations.AddField(
            model_name='battlesoldierinturn',
            name='battle_soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleSoldier'),
        ),
        migrations.AddField(
            model_name='battlesoldierinturn',
            name='battle_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
        ),
        migrations.AddField(
            model_name='battlesoldier',
            name='battle_contubernium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContubernium'),
        ),
        migrations.AddField(
            model_name='battlesoldier',
            name='world_npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.NPC'),
        ),
        migrations.AddField(
            model_name='battleside',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle'),
        ),
        migrations.AddField(
            model_name='battleorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='battleorganization',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleSide'),
        ),
        migrations.AddField(
            model_name='battleobjectinturn',
            name='battle_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleObject'),
        ),
        migrations.AddField(
            model_name='battleobjectinturn',
            name='battle_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
        ),
        migrations.AddField(
            model_name='battleobject',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle'),
        ),
        migrations.AddField(
            model_name='battleformation',
            name='battle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.Battle'),
        ),
        migrations.AddField(
            model_name='battleformation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='battle_contubernium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContubernium'),
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='battle_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='battle_unit_in_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnitInTurn'),
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='contubernium_attacked_this_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContuberniumInTurn'),
        ),
        migrations.AddField(
            model_name='battlecontubernium',
            name='battle_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnit'),
        ),
        migrations.AddField(
            model_name='battlecharacterinturn',
            name='battle_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacter'),
        ),
        migrations.AddField(
            model_name='battlecharacterinturn',
            name='battle_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
        ),
        migrations.AddField(
            model_name='battlecharacter',
            name='battle_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleOrganization'),
        ),
        migrations.AddField(
            model_name='battlecharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character'),
        ),
        migrations.AddField(
            model_name='battle',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tile'),
        ),
        migrations.AlterUniqueTogether(
            name='battleturn',
            unique_together=set([('battle', 'num')]),
        ),
        migrations.AlterIndexTogether(
            name='battleobjectinturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AlterUniqueTogether(
            name='battleformation',
            unique_together=set([('organization', 'battle')]),
        ),
        migrations.AlterUniqueTogether(
            name='battlecontuberniuminturn',
            unique_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
    ]
