# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
            ],
        ),
        migrations.CreateModel(
            name='BattleObjectInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('battle_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleObject')),
                ('battle_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn')),
            ],
        ),
    ]
