# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_battleobject_battleobjectinturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=15)),
                ('target_location_x', models.IntegerField(null=True)),
                ('target_location_z', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('battle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Order')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='battleturn',
            unique_together=set([('battle', 'num')]),
        ),
        migrations.AlterIndexTogether(
            name='battleobjectinturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AddField(
            model_name='battleunitinturn',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.Order'),
        ),
        migrations.AlterIndexTogether(
            name='battleunitinturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AddField(
            model_name='battleunit',
            name='orders',
            field=models.ManyToManyField(through='battle.OrderListElement', to='battle.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderlistelement',
            unique_together=set([('battle_unit', 'position')]),
        ),
    ]
