# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20171119_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='what',
            field=models.CharField(choices=[('stand', 'stand'), ('move', 'move'), ('flee', 'flee'), ('charge', 'charge'), ('formation', 'advance maintaining formation'), ('ranged and charge', 'ranged attack, then charge'), ('ranged and flee', 'ranged attack, then flee'), ('ranged and stand', 'ranged attack, then stand'), ('stand and keep distance', 'stand and keep distance')], max_length=15),
        ),
    ]
