# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_battlesoldierinturn_wound_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='battle_organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleOrganization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleunit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacter'),
        ),
    ]
