# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20170504_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderlistelement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderlistelement',
            name='battle_unit',
        ),
        migrations.RemoveField(
            model_name='orderlistelement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='battleunit',
            name='orders',
        ),
        migrations.AlterField(
            model_name='battleunitinturn',
            name='battle_character_in_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacterInTurn'),
        ),
        migrations.DeleteModel(
            name='OrderListElement',
        ),
    ]
