# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_battleunit_in_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecharacter',
            name='present_in_battle',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
