# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0006_battleunit_world_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='starting_x_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battleunit',
            name='starting_z_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
