# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_auto_20161030_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecharacter',
            name='z',
            field=models.BooleanField(default=False),
        ),
    ]
