# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_worldunit_generation_size'),
        ('battle', '0009_auto_20161113_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='tile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.Tile'),
            preserve_default=False,
        ),
    ]
