# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_auto_20171015_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleunitinturn',
            name='ammo_remaining',
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='ammo_remaining',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
