# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_auto_20170403_0007'),
        ('battle', '0010_auto_20170403_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='ready',
        ),
        migrations.AlterUniqueTogether(
            name='battleorganization',
            unique_together=set([('battle', 'organization')]),
        ),
    ]
