# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_auto_20170403_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battlecharacter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battlecharacter',
            name='character',
        ),
        migrations.RemoveField(
            model_name='battleobject',
            name='battle',
        ),
        migrations.AlterIndexTogether(
            name='battleobjectinturn',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='battleobjectinturn',
            name='battle_object',
        ),
        migrations.RemoveField(
            model_name='battleobjectinturn',
            name='battle_turn',
        ),
        migrations.AlterUniqueTogether(
            name='battleturn',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='battleturn',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battleunit',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='battleunit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='battleunit',
            name='world_unit',
        ),
        migrations.AlterIndexTogether(
            name='battleunitinturn',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='battleunitinturn',
            name='battle_turn',
        ),
        migrations.RemoveField(
            model_name='battleunitinturn',
            name='battle_unit',
        ),
        migrations.RemoveField(
            model_name='battleunitinturn',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='orderlistelement',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderlistelement',
            name='battle_unit',
        ),
        migrations.RemoveField(
            model_name='orderlistelement',
            name='order',
        ),
        migrations.DeleteModel(
            name='BattleCharacter',
        ),
        migrations.DeleteModel(
            name='BattleObject',
        ),
        migrations.DeleteModel(
            name='BattleObjectInTurn',
        ),
        migrations.DeleteModel(
            name='BattleTurn',
        ),
        migrations.DeleteModel(
            name='BattleUnit',
        ),
        migrations.DeleteModel(
            name='BattleUnitInTurn',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderListElement',
        ),
    ]
