# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_auto_20171025_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='attack_type_this_turn',
            field=models.CharField(blank=True, choices=[('melee', 'melee attack'), ('ranged', 'ranged attack')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='contubernium_attacked_this_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContuberniumInTurn'),
        ),
    ]
