# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0029_worldunit_generation_size'),
        ('battle', '0012_auto_20170403_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleOrganization')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Character')),
            ],
        ),
        migrations.CreateModel(
            name='BattleObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
            ],
        ),
        migrations.CreateModel(
            name='BattleObjectInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('battle_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleObject')),
            ],
        ),
        migrations.CreateModel(
            name='BattleTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
            ],
        ),
        migrations.CreateModel(
            name='BattleUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_x_pos', models.IntegerField(default=0)),
                ('starting_z_pos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BattleUnitInTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.IntegerField()),
                ('z_pos', models.IntegerField()),
                ('battle_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn')),
                ('battle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=15)),
                ('target_location_x', models.IntegerField(null=True)),
                ('target_location_z', models.IntegerField(null=True)),
                ('done', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('battle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Order')),
            ],
        ),
        migrations.AddField(
            model_name='battleunitinturn',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.Order'),
        ),
        migrations.AddField(
            model_name='battleunit',
            name='orders',
            field=models.ManyToManyField(through='battle.OrderListElement', to='battle.Order'),
        ),
        migrations.AddField(
            model_name='battleunit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacter'),
        ),
        migrations.AddField(
            model_name='battleunit',
            name='world_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.WorldUnit'),
        ),
        migrations.AddField(
            model_name='battleobjectinturn',
            name='battle_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
        ),
        migrations.AlterUniqueTogether(
            name='orderlistelement',
            unique_together=set([('battle_unit', 'position')]),
        ),
        migrations.AlterIndexTogether(
            name='battleunitinturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AlterUniqueTogether(
            name='battleturn',
            unique_together=set([('battle', 'num')]),
        ),
        migrations.AlterIndexTogether(
            name='battleobjectinturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AlterUniqueTogether(
            name='battlecharacter',
            unique_together=set([('battle_organization', 'character')]),
        ),
    ]
