# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0014_auto_20170403_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BattleNPC',
            new_name='BattleSoldier',
        ),
        migrations.RenameModel(
            old_name='BattleNPCInTurn',
            new_name='BattleSoldierInTurn',
        ),
    ]
