# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20170404_1704'),
        ('battle', '0016_auto_20170404_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleFormation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(choices=[('line', 'line'), ('column', 'column'), ('square', 'square'), ('wedge', 'wedge'), ('iwedge', 'iwedge')], max_length=15)),
                ('element_size', models.IntegerField()),
                ('spacing', models.IntegerField()),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='battleformation',
            unique_together=set([('organization', 'battle')]),
        ),
    ]
