# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0017_auto_20170404_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleformation',
            name='element_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battleformation',
            name='spacing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
