# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0018_auto_20170404_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Battle')),
            ],
        ),
        migrations.RemoveField(
            model_name='battleorganizationinturn',
            name='battle_organization',
        ),
        migrations.RemoveField(
            model_name='battleorganizationinturn',
            name='battle_turn',
        ),
        migrations.RemoveField(
            model_name='battlecharacterinturn',
            name='battle_organization_in_turn',
        ),
        migrations.AlterUniqueTogether(
            name='battlecharacter',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='battleorganization',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='BattleOrganizationInTurn',
        ),
        migrations.RemoveField(
            model_name='battleorganization',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battleorganization',
            name='z',
        ),
        migrations.AddField(
            model_name='battleorganization',
            name='side',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleSide'),
            preserve_default=False,
        ),
    ]
