# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0019_auto_20170405_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
