# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0020_battle_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='starting_manpower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
