# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0021_battleunit_starting_manpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='battle_side',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleSide'),
            preserve_default=False,
        ),
    ]
