# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0022_battleunit_battle_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontubernium',
            name='starting_x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlecontubernium',
            name='starting_z_pos',
            field=models.IntegerField(default=0),
        ),
    ]
