# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0023_auto_20170410_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='battle_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='x_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='z_pos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlesoldierinturn',
            name='battle_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleTurn'),
            preserve_default=False,
        ),
    ]
