# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0024_auto_20170410_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='end_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='start_turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
