# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0025_auto_20170410_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleunit',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battleunit',
            name='type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
