# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0027_auto_20170413_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='battle_unit_in_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleUnitInTurn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlesoldierinturn',
            name='battle_contubernium_in_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleContuberniumInTurn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battleunitinturn',
            name='battle_character_in_turn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='battle.BattleCharacterInTurn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='what',
            field=models.CharField(choices=[('stand', 'stand'), ('move', 'move'), ('flee', 'flee'), ('charge', 'charge'), ('formation', 'formation'), ('ranged', 'ranged')], max_length=15),
        ),
    ]
