# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0028_auto_20170413_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontubernium',
            name='x_offset_to_formation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlecontubernium',
            name='x_offset_to_unit',
            field=models.IntegerField(default=0, help_text='Offset to BattleUnit starting_pos'),
        ),
        migrations.AddField(
            model_name='battlecontubernium',
            name='z_offset_to_formation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlecontubernium',
            name='z_offset_to_unit',
            field=models.IntegerField(default=0),
        ),
    ]
