# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0029_auto_20170413_1259'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='battlecontuberniuminturn',
            index_together=set([('battle_turn', 'x_pos', 'z_pos')]),
        ),
        migrations.AlterIndexTogether(
            name='battleunitinturn',
            index_together=set([]),
        ),
    ]
