# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0031_auto_20170414_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecontuberniuminturn',
            name='moved_this_turn',
            field=models.BooleanField(default=False),
        ),
    ]
